/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ubicua;

import java.util.ArrayList;
import javax.swing.JLabel;

/**
 *
 * @author Don Portatil
 */
public class VistaGlobal extends javax.swing.JFrame {

    /**
     * Creates new form VistaGlobal
     */
    
    public VistaGlobal() {
        initComponents(); 

         //Iconos de linea de bus azul escondidos
        this.busazul2.setVisible(false);
        this.busazul3.setVisible(false);
        this.busazul4.setVisible(false);
        this.busazul5.setVisible(false);
        this.busazul6.setVisible(false);
        this.busazul7.setVisible(false);
        this.busazul8.setVisible(false);
        this.busazul9.setVisible(false);
        this.busazul10.setVisible(false);
        this.busazul11.setVisible(false);

        //Iconos de linea de bus escondidos
        this.busrojo2.setVisible(false);
        this.busrojo3.setVisible(false);
        this.busrojo4.setVisible(false);
        this.busrojo5.setVisible(false);
        this.busrojo6.setVisible(false);
        this.busrojo7.setVisible(false);
        this.busrojo8.setVisible(false);
        this.busrojo9.setVisible(false);
        this.busrojo10.setVisible(false);
        this.busrojo11.setVisible(false);
        this.busrojo12.setVisible(false);
        this.busrojo13.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel13 = new javax.swing.JPanel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        Zona1 = new javax.swing.JPanel();
        Zona2 = new javax.swing.JPanel();
        Zona3 = new javax.swing.JPanel();
        Zona4 = new javax.swing.JPanel();
        Zona5 = new javax.swing.JPanel();
        Salida = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        rotonda = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jPanel35 = new javax.swing.JPanel();
        jPanel36 = new javax.swing.JPanel();
        jPanel37 = new javax.swing.JPanel();
        jPanel38 = new javax.swing.JPanel();
        busrojo1 = new javax.swing.JLabel();
        busrojo2 = new javax.swing.JLabel();
        busrojo3 = new javax.swing.JLabel();
        busrojo4 = new javax.swing.JLabel();
        busrojo5 = new javax.swing.JLabel();
        busrojo6 = new javax.swing.JLabel();
        busrojo7 = new javax.swing.JLabel();
        busrojo8 = new javax.swing.JLabel();
        busrojo9 = new javax.swing.JLabel();
        busrojo10 = new javax.swing.JLabel();
        busrojo11 = new javax.swing.JLabel();
        busrojo12 = new javax.swing.JLabel();
        busrojo13 = new javax.swing.JLabel();
        busazul1 = new javax.swing.JLabel();
        busazul2 = new javax.swing.JLabel();
        busazul3 = new javax.swing.JLabel();
        busazul4 = new javax.swing.JLabel();
        busazul5 = new javax.swing.JLabel();
        busazul6 = new javax.swing.JLabel();
        busazul7 = new javax.swing.JLabel();
        busazul8 = new javax.swing.JLabel();
        busazul9 = new javax.swing.JLabel();
        busazul10 = new javax.swing.JLabel();
        busazul11 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setBackground(new java.awt.Color(255, 255, 255));
        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(null);

        Zona1.setBackground(new java.awt.Color(102, 255, 102));

        javax.swing.GroupLayout Zona1Layout = new javax.swing.GroupLayout(Zona1);
        Zona1.setLayout(Zona1Layout);
        Zona1Layout.setHorizontalGroup(
            Zona1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Zona1Layout.setVerticalGroup(
            Zona1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(Zona1);
        Zona1.setBounds(190, 140, 630, 224);

        Zona2.setBackground(new java.awt.Color(102, 255, 102));

        javax.swing.GroupLayout Zona2Layout = new javax.swing.GroupLayout(Zona2);
        Zona2.setLayout(Zona2Layout);
        Zona2Layout.setHorizontalGroup(
            Zona2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        Zona2Layout.setVerticalGroup(
            Zona2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 172, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(Zona2);
        Zona2.setBounds(190, 480, 630, 172);

        Zona3.setBackground(new java.awt.Color(102, 255, 102));

        javax.swing.GroupLayout Zona3Layout = new javax.swing.GroupLayout(Zona3);
        Zona3.setLayout(Zona3Layout);
        Zona3Layout.setHorizontalGroup(
            Zona3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );
        Zona3Layout.setVerticalGroup(
            Zona3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(Zona3);
        Zona3.setBounds(910, 480, 188, 172);

        Zona4.setBackground(new java.awt.Color(102, 255, 102));

        javax.swing.GroupLayout Zona4Layout = new javax.swing.GroupLayout(Zona4);
        Zona4.setLayout(Zona4Layout);
        Zona4Layout.setHorizontalGroup(
            Zona4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
        );
        Zona4Layout.setVerticalGroup(
            Zona4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(Zona4);
        Zona4.setBounds(910, 140, 186, 90);

        Zona5.setBackground(new java.awt.Color(102, 255, 102));

        javax.swing.GroupLayout Zona5Layout = new javax.swing.GroupLayout(Zona5);
        Zona5.setLayout(Zona5Layout);
        Zona5Layout.setHorizontalGroup(
            Zona5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );
        Zona5Layout.setVerticalGroup(
            Zona5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(Zona5);
        Zona5.setBounds(910, 280, 185, 98);

        Salida.setText("Salir");
        Salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalidaActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(Salida);
        Salida.setBounds(1100, 20, 100, 25);

        jButton2.setBackground(new java.awt.Color(255, 255, 0));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton2);
        jButton2.setBounds(800, 440, 30, 30);

        jButton3.setBackground(new java.awt.Color(255, 255, 0));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton3);
        jButton3.setBounds(920, 100, 30, 30);

        jButton4.setBackground(new java.awt.Color(255, 255, 0));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton4);
        jButton4.setBounds(650, 100, 30, 30);

        jButton5.setBackground(new java.awt.Color(255, 255, 0));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton5);
        jButton5.setBounds(320, 100, 30, 30);

        jButton6.setBackground(new java.awt.Color(255, 255, 0));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton6);
        jButton6.setBounds(150, 210, 30, 30);

        jButton7.setBackground(new java.awt.Color(255, 255, 0));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton7);
        jButton7.setBounds(150, 340, 30, 30);

        jButton8.setBackground(new java.awt.Color(255, 255, 0));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton8);
        jButton8.setBounds(150, 470, 30, 30);

        jButton9.setBackground(new java.awt.Color(255, 255, 0));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton9);
        jButton9.setBounds(200, 660, 30, 30);

        jButton10.setBackground(new java.awt.Color(255, 255, 0));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton10);
        jButton10.setBounds(460, 660, 30, 30);

        jButton11.setBackground(new java.awt.Color(255, 255, 0));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton11);
        jButton11.setBounds(760, 660, 30, 30);

        jButton12.setBackground(new java.awt.Color(255, 255, 0));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton12);
        jButton12.setBounds(960, 660, 30, 30);

        jButton13.setBackground(new java.awt.Color(255, 255, 0));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton13);
        jButton13.setBounds(1110, 320, 30, 30);

        jButton14.setBackground(new java.awt.Color(255, 255, 0));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton14);
        jButton14.setBounds(1110, 510, 30, 30);

        jButton15.setBackground(new java.awt.Color(255, 255, 0));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton15);
        jButton15.setBounds(1110, 170, 30, 30);

        jButton16.setBackground(new java.awt.Color(255, 255, 0));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton16);
        jButton16.setBounds(970, 240, 30, 30);

        jButton17.setBackground(new java.awt.Color(255, 255, 0));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton17);
        jButton17.setBounds(830, 270, 30, 30);

        jButton18.setBackground(new java.awt.Color(255, 255, 0));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton18);
        jButton18.setBounds(760, 370, 30, 30);

        jButton19.setBackground(new java.awt.Color(255, 255, 0));
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton19);
        jButton19.setBounds(520, 370, 30, 30);

        jButton20.setBackground(new java.awt.Color(255, 255, 0));
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton20);
        jButton20.setBounds(310, 370, 30, 30);

        jButton21.setBackground(new java.awt.Color(255, 255, 0));
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton21);
        jButton21.setBounds(360, 440, 30, 30);

        jButton22.setBackground(new java.awt.Color(255, 255, 0));
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton22);
        jButton22.setBounds(570, 440, 30, 30);

        rotonda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ubicua/rotonda.png"))); // NOI18N
        jInternalFrame1.getContentPane().add(rotonda);
        rotonda.setBounds(130, 390, 70, 64);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(jPanel1);
        jPanel1.setBounds(180, 370, 120, 10);

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(jPanel2);
        jPanel2.setBounds(90, 370, 50, 10);

        jPanel3.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(jPanel3);
        jPanel3.setBounds(90, 370, 10, 90);

        jPanel4.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(jPanel4);
        jPanel4.setBounds(90, 460, 50, 10);

        jPanel5.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(jPanel5);
        jPanel5.setBounds(190, 460, 160, 10);

        jPanel6.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(jPanel6);
        jPanel6.setBounds(400, 460, 160, 10);

        jPanel7.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(jPanel7);
        jPanel7.setBounds(610, 460, 180, 10);

        jPanel8.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(jPanel8);
        jPanel8.setBounds(840, 460, 290, 10);

        jPanel9.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(jPanel9);
        jPanel9.setBounds(1130, 360, 10, 110);

        jPanel10.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(jPanel10);
        jPanel10.setBounds(1130, 240, 10, 70);

        jPanel11.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(jPanel11);
        jPanel11.setBounds(1010, 240, 120, 10);

        jPanel12.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(jPanel12);
        jPanel12.setBounds(840, 240, 120, 10);

        jPanel14.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(jPanel14);
        jPanel14.setBounds(840, 310, 10, 70);

        jPanel15.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(jPanel15);
        jPanel15.setBounds(800, 370, 50, 10);

        jPanel16.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(jPanel16);
        jPanel16.setBounds(560, 370, 190, 10);

        jPanel17.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(jPanel17);
        jPanel17.setBounds(350, 370, 160, 10);

        jPanel18.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(jPanel18);
        jPanel18.setBounds(840, 250, 10, 10);

        jPanel19.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(jPanel19);
        jPanel19.setBounds(160, 110, 10, 90);

        jPanel20.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(jPanel20);
        jPanel20.setBounds(170, 110, 140, 10);

        jPanel21.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(jPanel21);
        jPanel21.setBounds(360, 110, 280, 10);

        jPanel22.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(jPanel22);
        jPanel22.setBounds(690, 110, 220, 10);

        jPanel23.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(jPanel23);
        jPanel23.setBounds(960, 110, 170, 10);

        jPanel24.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(jPanel24);
        jPanel24.setBounds(1120, 120, 10, 40);

        jPanel25.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(jPanel25);
        jPanel25.setBounds(1120, 210, 10, 100);

        jPanel26.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(jPanel26);
        jPanel26.setBounds(1120, 360, 10, 140);

        jPanel27.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(jPanel27);
        jPanel27.setBounds(1120, 550, 10, 130);

        jPanel28.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(jPanel28);
        jPanel28.setBounds(1000, 670, 120, 10);

        jPanel29.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(jPanel29);
        jPanel29.setBounds(800, 670, 150, 10);

        jPanel30.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(jPanel30);
        jPanel30.setBounds(500, 670, 250, 10);

        jPanel31.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(jPanel31);
        jPanel31.setBounds(240, 670, 210, 10);

        jPanel33.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(jPanel33);
        jPanel33.setBounds(160, 510, 10, 170);

        jPanel34.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel34Layout = new javax.swing.GroupLayout(jPanel34);
        jPanel34.setLayout(jPanel34Layout);
        jPanel34Layout.setHorizontalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel34Layout.setVerticalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(jPanel34);
        jPanel34.setBounds(170, 670, 20, 10);

        jPanel35.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel35Layout = new javax.swing.GroupLayout(jPanel35);
        jPanel35.setLayout(jPanel35Layout);
        jPanel35Layout.setHorizontalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel35Layout.setVerticalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(jPanel35);
        jPanel35.setBounds(70, 480, 70, 10);

        jPanel36.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel36Layout = new javax.swing.GroupLayout(jPanel36);
        jPanel36.setLayout(jPanel36Layout);
        jPanel36Layout.setHorizontalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel36Layout.setVerticalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(jPanel36);
        jPanel36.setBounds(70, 360, 10, 120);

        jPanel37.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel37Layout = new javax.swing.GroupLayout(jPanel37);
        jPanel37.setLayout(jPanel37Layout);
        jPanel37Layout.setHorizontalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel37Layout.setVerticalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(jPanel37);
        jPanel37.setBounds(70, 350, 70, 10);

        jPanel38.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel38Layout = new javax.swing.GroupLayout(jPanel38);
        jPanel38.setLayout(jPanel38Layout);
        jPanel38Layout.setHorizontalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel38Layout.setVerticalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(jPanel38);
        jPanel38.setBounds(160, 250, 10, 80);

        busrojo1.setForeground(new java.awt.Color(255, 255, 255));
        busrojo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ubicua/bus.png"))); // NOI18N
        jInternalFrame1.getContentPane().add(busrojo1);
        busrojo1.setBounds(140, 80, 24, 24);

        busrojo2.setForeground(new java.awt.Color(255, 255, 255));
        busrojo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ubicua/bus.png"))); // NOI18N
        jInternalFrame1.getContentPane().add(busrojo2);
        busrojo2.setBounds(490, 80, 24, 24);

        busrojo3.setForeground(new java.awt.Color(255, 255, 255));
        busrojo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ubicua/bus.png"))); // NOI18N
        jInternalFrame1.getContentPane().add(busrojo3);
        busrojo3.setBounds(780, 80, 24, 24);

        busrojo4.setForeground(new java.awt.Color(255, 255, 255));
        busrojo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ubicua/bus.png"))); // NOI18N
        jInternalFrame1.getContentPane().add(busrojo4);
        busrojo4.setBounds(1090, 80, 24, 24);

        busrojo5.setForeground(new java.awt.Color(255, 255, 255));
        busrojo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ubicua/bus.png"))); // NOI18N
        jInternalFrame1.getContentPane().add(busrojo5);
        busrojo5.setBounds(1150, 250, 24, 24);

        busrojo6.setForeground(new java.awt.Color(255, 255, 255));
        busrojo6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ubicua/bus.png"))); // NOI18N
        jInternalFrame1.getContentPane().add(busrojo6);
        busrojo6.setBounds(1150, 430, 24, 24);

        busrojo7.setForeground(new java.awt.Color(255, 255, 255));
        busrojo7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ubicua/bus.png"))); // NOI18N
        jInternalFrame1.getContentPane().add(busrojo7);
        busrojo7.setBounds(1140, 630, 24, 24);

        busrojo8.setForeground(new java.awt.Color(255, 255, 255));
        busrojo8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ubicua/bus.png"))); // NOI18N
        jInternalFrame1.getContentPane().add(busrojo8);
        busrojo8.setBounds(880, 690, 24, 24);

        busrojo9.setForeground(new java.awt.Color(255, 255, 255));
        busrojo9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ubicua/bus.png"))); // NOI18N
        jInternalFrame1.getContentPane().add(busrojo9);
        busrojo9.setBounds(610, 690, 24, 24);

        busrojo10.setForeground(new java.awt.Color(255, 255, 255));
        busrojo10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ubicua/bus.png"))); // NOI18N
        jInternalFrame1.getContentPane().add(busrojo10);
        busrojo10.setBounds(330, 690, 24, 24);

        busrojo11.setForeground(new java.awt.Color(255, 255, 255));
        busrojo11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ubicua/bus.png"))); // NOI18N
        jInternalFrame1.getContentPane().add(busrojo11);
        busrojo11.setBounds(130, 590, 24, 24);

        busrojo12.setForeground(new java.awt.Color(255, 255, 255));
        busrojo12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ubicua/bus.png"))); // NOI18N
        jInternalFrame1.getContentPane().add(busrojo12);
        busrojo12.setBounds(40, 410, 24, 24);

        busrojo13.setForeground(new java.awt.Color(255, 255, 255));
        busrojo13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ubicua/bus.png"))); // NOI18N
        jInternalFrame1.getContentPane().add(busrojo13);
        busrojo13.setBounds(130, 280, 24, 24);

        busazul1.setForeground(new java.awt.Color(255, 255, 255));
        busazul1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ubicua/bus.png"))); // NOI18N
        jInternalFrame1.getContentPane().add(busazul1);
        busazul1.setBounds(1060, 250, 24, 24);

        busazul2.setForeground(new java.awt.Color(255, 255, 255));
        busazul2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ubicua/bus.png"))); // NOI18N
        jInternalFrame1.getContentPane().add(busazul2);
        busazul2.setBounds(870, 210, 24, 24);

        busazul3.setForeground(new java.awt.Color(255, 255, 255));
        busazul3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ubicua/bus.png"))); // NOI18N
        jInternalFrame1.getContentPane().add(busazul3);
        busazul3.setBounds(860, 360, 24, 24);

        busazul4.setForeground(new java.awt.Color(255, 255, 255));
        busazul4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ubicua/bus.png"))); // NOI18N
        jInternalFrame1.getContentPane().add(busazul4);
        busazul4.setBounds(620, 390, 24, 24);

        busazul5.setForeground(new java.awt.Color(255, 255, 255));
        busazul5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ubicua/bus.png"))); // NOI18N
        jInternalFrame1.getContentPane().add(busazul5);
        busazul5.setBounds(420, 390, 24, 24);

        busazul6.setForeground(new java.awt.Color(255, 255, 255));
        busazul6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ubicua/bus.png"))); // NOI18N
        jInternalFrame1.getContentPane().add(busazul6);
        busazul6.setBounds(230, 390, 24, 24);

        busazul7.setForeground(new java.awt.Color(255, 255, 255));
        busazul7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ubicua/bus.png"))); // NOI18N
        jInternalFrame1.getContentPane().add(busazul7);
        busazul7.setBounds(100, 380, 24, 24);

        busazul8.setForeground(new java.awt.Color(255, 255, 255));
        busazul8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ubicua/bus.png"))); // NOI18N
        jInternalFrame1.getContentPane().add(busazul8);
        busazul8.setBounds(270, 430, 24, 24);

        busazul9.setForeground(new java.awt.Color(255, 255, 255));
        busazul9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ubicua/bus.png"))); // NOI18N
        jInternalFrame1.getContentPane().add(busazul9);
        busazul9.setBounds(480, 430, 24, 24);

        busazul10.setForeground(new java.awt.Color(255, 255, 255));
        busazul10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ubicua/bus.png"))); // NOI18N
        jInternalFrame1.getContentPane().add(busazul10);
        busazul10.setBounds(690, 430, 24, 24);

        busazul11.setForeground(new java.awt.Color(255, 255, 255));
        busazul11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ubicua/bus.png"))); // NOI18N
        jInternalFrame1.getContentPane().add(busazul11);
        busazul11.setBounds(1020, 430, 24, 24);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.DEFAULT_SIZE, 1234, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalidaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalidaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       Panel x = new Panel();
       x.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       Panel x = new Panel();
       x.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Panel x = new Panel();
       x.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Panel x = new Panel();
       x.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       Panel x = new Panel();
       x.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Panel x = new Panel();
       x.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
       Panel x = new Panel();
       x.setVisible(true);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
       Panel x = new Panel();
       x.setVisible(true);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
      Panel x = new Panel();
       x.setVisible(true);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
       Panel x = new Panel();
       x.setVisible(true);
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
      Panel x = new Panel();
       x.setVisible(true);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Panel x = new Panel();
       x.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
       Panel x = new Panel();
       x.setVisible(true);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
       Panel x = new Panel();
       x.setVisible(true);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        Panel x = new Panel();
       x.setVisible(true);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        Panel x = new Panel();
       x.setVisible(true);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        Panel x = new Panel();
       x.setVisible(true);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        Panel x = new Panel();
       x.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        Panel x = new Panel();
       x.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        Panel x = new Panel();
       x.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       Panel x = new Panel();
       x.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaGlobal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaGlobal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaGlobal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaGlobal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaGlobal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Salida;
    private javax.swing.JPanel Zona1;
    private javax.swing.JPanel Zona2;
    private javax.swing.JPanel Zona3;
    private javax.swing.JPanel Zona4;
    private javax.swing.JPanel Zona5;
    private javax.swing.JLabel busazul1;
    private javax.swing.JLabel busazul10;
    private javax.swing.JLabel busazul11;
    private javax.swing.JLabel busazul2;
    private javax.swing.JLabel busazul3;
    private javax.swing.JLabel busazul4;
    private javax.swing.JLabel busazul5;
    private javax.swing.JLabel busazul6;
    private javax.swing.JLabel busazul7;
    private javax.swing.JLabel busazul8;
    private javax.swing.JLabel busazul9;
    private javax.swing.JLabel busrojo1;
    private javax.swing.JLabel busrojo10;
    private javax.swing.JLabel busrojo11;
    private javax.swing.JLabel busrojo12;
    private javax.swing.JLabel busrojo13;
    private javax.swing.JLabel busrojo2;
    private javax.swing.JLabel busrojo3;
    private javax.swing.JLabel busrojo4;
    private javax.swing.JLabel busrojo5;
    private javax.swing.JLabel busrojo6;
    private javax.swing.JLabel busrojo7;
    private javax.swing.JLabel busrojo8;
    private javax.swing.JLabel busrojo9;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel rotonda;
    // End of variables declaration//GEN-END:variables
}
